export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const GET_WORKSPACES = 'GET_WORKSPACES';
export const SET_ACTIVE_CHANNEL = 'SET_ACTIVE_CHANNEL';
export const GET_WORKSPACE_DATA = 'GET_WORKSPACE_DATA';
export const GET_CHANNEL_DATA = 'GET_CHANNEL_DATA';
export const NEW_CHANNEL_MESSAGE = 'NEW_CHANNEL_MESSAGE';
