export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const GET_WORKSPACES = 'GET_WORKSPACES';
export const SET_ACTIVE_CHANNEL = 'SET_ACTIVE_CHANNEL';
export const GET_WORKSPACE_DATA = 'GET_WORKSPACE_DATA';
